/**
  ******************************************************************************
  * @file    weather.h
  * @brief   Weather station sensor + display module for X-NUCLEO-IKS01A3.
  *          User-owned, sits on top of the IKS01A3 BSP generated by CubeMX.
  ******************************************************************************
  */
#ifndef WEATHER_H
#define WEATHER_H

#include <stdint.h>
#include "stm32l1xx_hal.h"

/* Maximum length of the city name buffer (including null terminator) */
#define WEATHER_CITY_LEN 32

/* One weather observation */
typedef struct {
    float   temperature_c;
    float   humidity_pct;
    float   pressure_hpa;
    uint8_t valid;          /* 1 = all sensors ok, 0 = at least one error */
} WeatherSample;

/* Initialize HTS221 (humidity + temp), LPS22HH (pressure), STTS751 (temp).
 * Returns 0 on success, negative if any sensor init fails (still tries the others). */
int  Weather_InitSensors(void);

/* Read all enabled sensors into *out. Returns 0 on success. */
int  Weather_ReadSensors(WeatherSample *out);

/* Drive status LEDs based on sample validity. */
void Weather_UpdateLeds(const WeatherSample *s);

/* Print one formatted telemetry line over UART, prefixed with the city. */
void Weather_PrintUart(UART_HandleTypeDef *huart,
                       const char *city,
                       const WeatherSample *s);

#endif /* WEATHER_H */
